runtime: python37
service: default
handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html
  - url: /blog
    static_files: public/blog/index.html
    upload: public/blog/index.html
  - url: /assessment
    static_files: public/assessmeent/index.html
    upload: public/assessmeent/index.html
  - url: /(.*)
    static_files: public/\1
    upload: public/(.*)