runtime: python37
service: default
handlers:
  - url: /
    static_files: public/blog/index.html
    upload: public/events/index.html
  - url: /(.*)
    static_files: public/\1
    upload: public/(.*)